package dev.roocky.emitreetabs.ui;

import com.mojang.blaze3d.systems.RenderSystem;

import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.resources.ResourceLocation;

/**
 * The drawn icons, and the one way to paint them.
 *
 * <p>Every control in the tab bar and the sidebar used to borrow a font glyph — {@code ≡}, {@code
 * ×}, {@code ⚙}, {@code ◀}. That is why the bar looked unfinished: the glyphs are sized for text
 * rather than for a button, they land on whatever baseline the font decides, and one of them was
 * actively wrong — {@code ≡} is the vertical-tabs icon in every browser shipping today, so the
 * button that toggles crafting for every tree read as a layout switch.
 *
 * <p>The sheet is a white alpha mask, tinted at draw time. That is deliberate: the strip and the
 * sidebar already say a great deal with colour — dimmed, hovered, active, crafting, close-hover
 * red — and a pre-coloured sprite would have to be drawn once per state.
 *
 * <p>Authored in {@code art/icons/*.svg} and generated by {@code art/make_icons.py}. The PNG is
 * built from those sources; edit the SVG, not the sheet.
 */
public final class Icons {

	private static final ResourceLocation SHEET =
			new ResourceLocation("emitreetabs", "textures/gui/icons.png");
	private static final int SHEET_WIDTH = 64;
	private static final int SHEET_HEIGHT = 32;

	/** A rectangle on the sheet. Sizes differ because the controls they fill do. */
	public record Sprite(int u, int v, int width, int height) {
	}

	/** A 2x2 crafting grid with a check: crafting for every tree. */
	public static final Sprite CRAFT_ALL = new Sprite(0, 0, 12, 12);
	/** Forks the active tree into a new tab. */
	public static final Sprite NEW_TAB = new Sprite(12, 0, 12, 12);
	public static final Sprite SETTINGS = new Sprite(24, 0, 12, 12);
	/** The same check alone: crafting for the one tree whose marker this is. */
	public static final Sprite CRAFT_ONE = new Sprite(36, 0, 10, 10);
	public static final Sprite CLOSE = new Sprite(48, 0, 8, 8);
	/** Two bars. A parked group is set aside, not switched off. */
	public static final Sprite PARK = new Sprite(56, 0, 8, 8);
	public static final Sprite ARROW_LEFT = new Sprite(0, 16, 5, 8);
	public static final Sprite ARROW_RIGHT = new Sprite(6, 16, 5, 8);
	public static final Sprite CARET_RIGHT = new Sprite(12, 16, 4, 7);
	public static final Sprite CARET_DOWN = new Sprite(17, 16, 7, 4);

	private Icons() {
	}

	/** Paints a sprite with its top-left at {@code (x, y)}, tinted. */
	public static void draw(GuiGraphics graphics, Sprite sprite, int x, int y, int argb) {
		int alpha = (argb >>> 24) & 0xFF;
		// The palettes in this package are written 0xAARRGGBB, but a bare 0xRRGGBB would otherwise
		// paint nothing at all, which is a hard bug to see. Treat a missing alpha as opaque.
		float a = alpha == 0 ? 1f : alpha / 255f;
		RenderSystem.enableBlend();
		RenderSystem.defaultBlendFunc();
		graphics.setColor(((argb >> 16) & 0xFF) / 255f, ((argb >> 8) & 0xFF) / 255f,
				(argb & 0xFF) / 255f, a);
		graphics.blit(SHEET, x, y, sprite.u(), sprite.v(), sprite.width(), sprite.height(),
				SHEET_WIDTH, SHEET_HEIGHT);
		graphics.setColor(1f, 1f, 1f, 1f);
		RenderSystem.disableBlend();
	}

	/**
	 * Paints a sprite centred in a box.
	 *
	 * <p>Which is the whole point of drawing them: a glyph sits on a text baseline and has to be
	 * nudged by hand per control, and every one of those nudges was a different magic number.
	 */
	public static void centred(GuiGraphics graphics, Sprite sprite, int x, int y,
			int width, int height, int argb) {
		draw(graphics, sprite, x + (width - sprite.width()) / 2, y + (height - sprite.height()) / 2,
				argb);
	}
}
